import json, re, sys

# Translation dictionary for accounting terms and phrases
T = {
    # Common accounting terms
    "Debit": "借方",
    "Credit": "貸方",
    "Work in Process": "仕掛品",
    "Work in Process Inventory": "仕掛品棚卸資産",
    "Finished Goods": "製品",
    "Finished Goods Inventory": "製品棚卸資産",
    "Raw Materials": "原材料",
    "Raw Materials Inventory": "原材料棚卸資産",
    "Factory Overhead": "製造間接費",
    "Manufacturing Overhead": "製造間接費",
    "Cost of Goods Sold": "売上原価",
    "Cost of Goods Manufactured": "製品製造原価",
    "Cost of Goods Available for Sale": "販売可能商品原価",
    "Retained Earnings": "繰越利益剰余金",
    "Common Stock": "普通株式",
    "Treasury Stock": "自己株式",
    "Additional Paid-in Capital": "株式払込剰余金",
    "Accumulated Depreciation": "減価償却累計額",
    "Accounts Payable": "買掛金",
    "Accounts Receivable": "売掛金",
    "Cash": "現金",
    "Sales Revenue": "売上高",
    "Interest Revenue": "利息収益",
    "Interest Receivable": "未収利息",
    "Interest Payable": "未払利息",
    "Notes Receivable": "受取手形",
    "Notes Payable": "支払手形",
    "Bad Debt Expense": "貸倒損失",
    "Allowance for Doubtful Accounts": "貸倒引当金",
    "Depreciation Expense": "減価償却費",
    "Income Summary": "損益集計",
    "Dividends Payable": "未払配当金",
    "Inventory": "棚卸資産",
    "Purchases": "仕入",
    "Purchase Returns and Allowances": "仕入戻し及び値引",
    "Purchase Discounts": "仕入割引",
    "Sales Returns and Allowances": "売上値引及び返品",
    "Sales Discounts": "売上割引",
    "Unearned Revenue": "前受収益",
    "Prepaid Insurance": "前払保険料",
    "Insurance Expense": "保険料",
    "Freight In": "仕入運賃",
    "Freight Out": "発送運賃",
    "Delivery Expense": "配送費",
    "Property Dividends Payable": "未払現物配当金",
    "Bonus Expense": "賞与費用",
    "Provision for Bonuses Payable": "未払賞与引当金",
    "Construction in Progress": "建設仮勘定",
    "Net Income": "当期純利益",
    "Gross Profit": "売上総利益",
    "Net Sales": "純売上高",
    "Operating Expenses": "営業費用",
    "Selling Expenses": "販売費",
    "Administrative Expenses": "一般管理費",
    "Total Revenue": "総収益",
    "Total Expenses": "総費用",
    "Total Assets": "総資産",
    "Total Liabilities": "総負債",
    "Stockholders' Equity": "株主資本",
    "Current Assets": "流動資産",
    "Current Liabilities": "流動負債",
    "Intangible Assets": "無形資産",
    "Property, Plant, and Equipment": "有形固定資産",
    "Preferred Stock": "優先株式",
    "Common Stock Distributable": "株式配当未払",
    "Common Stock Subscribed": "普通株式引受済",
    "Subscriptions Receivable": "株式引受金",
    "Discount on Common Stock": "株式割引",
    "Land": "土地",
    "Building": "建物",
    "Equipment": "設備",
    "Salaries Expense": "給与費用",
    "Wages Payable": "未払給与",
    "Social Insurance Payable": "未払社会保険料",
    "Income Tax Expense": "法人税等",
    "Comprehensive Income": "包括利益",
    "Other Comprehensive Income": "その他の包括利益",
    "Prior Period Adjustment": "前期修正",
    "Salary Expense": "給与費用",
    "Partners' Capital": "組合員資本",
    "Partner, Drawings": "組合員引出金",
    "Partner, Capital": "組合員資本金",
    "Organization Expense": "創立費",
    "Compensation Expense": "報酬費用",
    "WIP": "仕掛品",
    "COGS": "売上原価",
    "COGM": "製品製造原価",
    "APIC": "株式払込剰余金",
    "R/E": "繰越利益剰余金",
    "DLH": "直接作業時間",
    "MH": "機械時間",
    "OH": "製造間接費",
    "VOH": "変動間接費",
    "EU": "換算量",
    "RIP": "材料・仕掛品",
    "Physical units": "物理単位数",
    "Operating income": "営業利益",
    "Earnings per share": "1株当たり利益",
    "Unfavorable": "不利",
    "Favorable": "有利",
    "Direct materials used": "直接材料費",
    "Direct labor": "直接労務費",
    "Beginning inventory": "期首棚卸",
    "Ending inventory": "期末棚卸",
    "Beginning WIP": "期首仕掛品",
    "Ending WIP": "期末仕掛品",
    "Beginning FG": "期首製品",
    "Ending FG": "期末製品",
    "Total manufacturing costs": "総製造費用",
    "Sales Returns": "売上返品",
    "Sales Allowance": "売上値引",
    "Raw and In Process Inventory": "材料・仕掛品棚卸資産",
    "Investments": "投資有価証券",
    "Appropriation for Plant Expansion": "工場拡張積立金",
    "Gain on disposal": "固定資産売却益",
    "Loss on disposal": "固定資産売却損",
    "Loss on Inventory": "棚卸資産評価損",
    "Marketable securities": "有価証券",
    "Deferred Tax Liability": "繰延税金負債",
    "Scrap Inventory": "仕損品棚卸資産",
    "Materials Inventory Shortage": "棚卸資産不足費",
    "Standard cost": "標準原価",
    "Actual cost": "実際原価",
    "Budgeted cost": "予算原価",
    "Budgeted Variable OH": "予算変動間接費",
    "Actual Variable OH": "実際変動間接費",
    "Standard Variable OH Rate": "標準変動間接費率",
    "Actual Variable OH Rate": "実際変動間接費率",
    "Standard Fixed OH": "標準固定間接費",
    "Budgeted Fixed OH": "予算固定間接費",
    "Actual Fixed OH": "実際固定間接費",
    "Applied Fixed OH": "配賦固定間接費",
    "Applied Overhead": "配賦間接費",
    "Applied VOH": "配賦変動間接費",
    "Stockholders' equity": "株主資本",
    "Depreciable cost": "減価償却対象原価",
    "Book value": "帳簿価額",
    "Salvage value": "残存価額",
    "Residual value": "残存価額",
    "Par value": "額面",
    "Stated value": "設定価額",
    "Market value": "時価",
    "Fair value": "公正価値",
    "Fair market value": "公正時価",
    "Historical cost": "取得原価",
    "Purchase price": "購入価額",
    "Contra asset": "対資産",
    "Contra revenue": "対収益",
    "Current ratio": "流動比率",
    "Quick ratio": "当座比率",
    "Working capital": "運転資本",
    "Extraordinary items": "特別損益",
    "Underapplied": "配賦不足",
    "Overapplied": "配賦超過",
    "Underallocated": "配賦不足",
    "Overallocated": "配賦超過",
    "Predetermined overhead rate": "予定間接費配賦率",
    "Activity-based costing": "活動基準原価計算",
    "Cost pool": "コストプール",
    "Cost driver": "コストドライバー",
    "High-low method": "高低点法",
    "Equivalent units": "換算量",
    "Process costing": "工程別原価計算",
    "Job-order costing": "ジョブオーダー原価計算",
    "Absorption costing": "吸収原価計算",
    "Variable costing": "変動原価計算",
    "Normal costing": "正常原価計算",
    "Actual costing": "実際原価計算",
    "Standard costing": "標準原価計算",
    "Backflush costing": "バックフラッシュ原価計算",
    "Operation costing": "オペレーション原価計算",
    "Joint products": "結合製品",
    "Split-off point": "分離点",
    "Spoilage": "仕損",
    "Scrap": "仕損品",
    "Weighted average method": "加重平均法",
    "FIFO method": "先入先出法",
    "Moving average method": "移動平均法",
    "Percentage-of-completion method": "完成率法",
    "Straight-line method": "定額法",
    "Declining balance method": "定率法",
    "Sum-of-the-years'-digits method": "級数法",
    "Units of production method": "生産高比例法",
    "Allowance method": "貸倒引当法",
    "Direct write-off method": "直接貸倒法",
    "Gross method": "総額法",
    "Net method": "正味法",
    "Periodic inventory system": "定期棚卸法",
    "Perpetual inventory system": "継続記録法",
    "Just-in-time": "JIT",
    "Statement of retained earnings": "繰越利益剰余金計算書",
    "Statement of cash flows": "キャッシュフロー計算書",
    "Income statement": "損益計算書",
    "Balance sheet": "貸借対照表",
    "Statement of Changes in Equity": "株主資本等変動計算書",
    "Limited partnership": "有限責任組合",
    "General partner": "無限責任組合員",
    "Limited partner": "有限責任組合員",
    "Corporation": "法人",
    "Partnership": "組合",
    "Callable preferred stock": "償還優先株式",
    "Convertible preferred stock": "転換優先株式",
    "Participating preferred stock": "参加的優先株式",
    "Cumulative preferred stock": "累積優先株式",
    "No-par stock": "無額面株式",
    "Stock dividend": "株式配当",
    "Stock split": "株式分割",
    "Property dividend": "現物配当",
    "Cash dividend": "現金配当",
    "Board of directors": "取締役会",
    "Trade discount": "数量値引",
    "Sales allowance": "売上値引",
    "Credit card fee": "クレジットカード手数料",
    "Credit sales": "掛け売上",
    "Bank reconciliation": "銀行勘定調整表",
    "Outstanding checks": "未決済小切手",
    "Deposits in transit": "未取立預金",
    "Warranty expense": "保証費用",
    "Warranty liability": "保証引当金",
    "Construction costs": "建設費用",
    "Percentage-of-sales method": "売上高基準法",
    "Aging of receivables": "売掛金 aging 法",
    "Bank balance": "銀行残高",
    "Counterbalancing error": "相殺誤り",
    "Non-counterbalancing error": "非相殺誤り",
    "Understated": "過小",
    "Overstated": "過大",
    "Understated,": "過小、",
    "Overstated,": "過大、",
    "Trademark": "商標権",
    "Goodwill": "のれん",
    "Patents": "特許権",
    "Copyrights": "著作権",
    "Plant-wide overhead rate": "全工場一括配賦率",
    "Departmental overhead rates": "部門間接費率",
    "Service department": "補助部門",
    "Production department": "生産部門",
    "Direct method": "直接法",
    "Step-down method": "段階法",
    "Reciprocal method": "相互配賦法",
    "Variable overhead spending variance": "変動間接費配賦差異",
    "Variable overhead efficiency variance": "変動間接費能率差異",
    "Fixed overhead budget variance": "固定間接費予算差異",
    "Fixed overhead volume variance": "操業度差異",
    "Labor rate variance": "労務費率差異",
    "Labor efficiency variance": "労務費時間差異",
    "Material price variance": "材料価格差異",
    "Material quantity variance": "材料数量差異",
    "Total labor cost variance": "総労務費差異",
    "Total material cost variance": "総材料費差異",
    "Total overhead variance": "総間接費差異",
    "Allocation base": "配賦基準",
    "Denominator level": "分母水準",
    "Conversion costs": "加工費",
    "Prime costs": "素原価",
    "Inventoriable cost": "棚卸資産原価",
    "Period cost": "期間費用",
    "Product cost": "製品原価",
    "Natural resources": "天然資源",
    "Depletion": "減耗",
    "Amortization": "償却",
    "Impairment": "減損",
    "Component depreciation": "コンポーネント減価償却",
    "Change in accounting estimate": "会計上の見積変更",
    "Change in accounting principle": "会計方針の変更",
    "Commercial substance": "実質的価値の移転",
    "Half-year convention": "半期規約",
    "Production cost report": "生産原価報告書",
    "Job order cost sheet": "ジョブ原価計算書",
    "Cost reconciliation": "原価配分の検証",
    "Transferred-in costs": "振替原価",
    "Sales value at split-off method": "分離点売価法",
    "Normal spoilage": "正常仕損",
    "Abnormal spoilage": "異常仕損",
    "Bonus to": "へのボーナス",
    "ex-dividend": "配当落ち",
    "Dividend revenue": "配当収益",
    "Gain on Stock Issuance": "株式発行益",
    "Loss on Treasury Stock": "自己株式処分損",
    "Gain on Sale of Treasury Stock": "自己株式売却益",
    "Retirement": "廃棄",
    "Liquidation": "清算",
    "Mutual agency": "相互代理",
    "Limited liability": "有限責任",
    "Continuous life": "永続的生命",
    "Separate legal entity": "独立した法的主体",
    "Double taxation": "二重課税",
    "Legal capital": "法定資本",
    "Call price": "償還価格",
    "Conversion ratio": "転換比率",
    "Subscription agreement": "株式引受契約",
    "Mature": "満期",
    "Maturity value": "満期価額",
    "Face value": "額面",
    "Principal": "元金",
    "Accrued interest": "発生利息",
    "Discount rate": "割引率",
    "Proceeds": "手取額",
    "Dishonored": "不渡り",
    "Endorsed": "裏書譲渡",
    "Discounting": "割引",
    "Uncollectible": "回収不能",
    "Write off": "貸倒処理",
    "Write-off": "貸倒処理",
    "Recovery": "回収",
    "Adjusting entry": "修正仕訳",
    "Journal entry": "仕訳",
    "Trade discount": "数量値引",
    "Quantity discount": "数量値引",
    "Credit terms": "支払条件",
    "FOB shipping point": "FOB甲地（元払）",
    "FOB destination": "FOB乙地（着払）",
    "Credit period": "信用期間",
    "Discount period": "割引期間",
    "Gross pay": "総支給額",
    "Net pay": "手取額",
    "Deductions": "控除",
    "Employer burden": "雇主負担",
    "Payroll taxes": "給与税",
    "Overtime premium": "残業割増",
    "Piece-rate": "歩合制",
    "Shift premium": "シフト割増",
    "Night shift differential": "夜勤差額",
    "Idle time": "アイドルタイム",
    "Time tickets": "作業時間票",
    "Learning curve": "学習曲線",
    "Guaranteed wage plan": "保証賃金制",
    "Differential piece-rate": "差別歩合制",
    "Efficiency ratio": "能率比",
    "Production run": "生産ロット",
    "Machine hours": "機械時間",
    "Direct labor hours": "直接作業時間",
    "Direct labor cost": "直接労務費",
    "Estimated total overhead": "見積総間接費",
    "Estimated total allocation base": "見積総配賦基準",
    "Actual total overhead": "実際総間接費",
    "Actual total allocation base": "実際総配賦基準",
    "Overhead applied": "配賦間接費",
    "Overhead variance": "間接費差異",
    "Cost per EU": "換算単位原価",
    "Equivalent units of production": "換算生産量",
    "Physical flow of units": "物理的流動",
    "Cost assignment": "原価配賦",
    "Transferred out": "振替済",
    "Materials requisition": "材料出庫票",
    "Purchase return": "仕入戻し",
    "Requisitioned": "払出",
    "Issued": "払出",
    "Purchase": "仕入",
    "Purchased": "仕入",
    "Receives": "受領",
    "Received": "受領",
    "Pays": "支払",
    "Paid": "支払済み",
    "Records": "記録",
    "Recorded": "記録済み",
    "Declared": "宣言済み",
    "Issues": "発行",
    "Issued": "発行済み",
    "Invests": "出資",
    "Invested": "出資済み",
    "Admitted": "加入",
    "Retires": "退職",
    "Retiring": "退職",
    "Reissues": "再発行",
    "Reissued": "再発行済み",
    "Declares": "宣言",
    "Appropriates": "積立",
    "Effects": "実施",
    "Donates": "寄贈",
    "Liquidates": "清算",
    "Retiring it": "廃棄する",
    "Calculated as": "次のように計算される",
    "Calculated for": "次について計算される",
    "The entry is": "仕訳は",
    "The correct entry is": "正しい仕訳は",
    "The correct entry to record the sale is": "売上記録の正しい仕訳は",
    "The appropriate account to record these costs is": "これらの費用を記録する適切な勘定は",
    "Is recorded by debiting": "次に借方記録される",
    "Is recorded as": "次のように記録される",
    "Should be charged to": "次に課すべきである",
    "Should be recorded as": "次のように記録すべきである",
    "Should be": "次であるべきである",
    "Is treated as": "次のように処理される",
    "Is reported on the": "次に記載される",
    "Is reported as": "次として報告される",
    "Are recorded as": "次のように記録される",
    "Is calculated as:": "次のように計算される：",
    "Is:": "次である：",
    "Are:": "次である：",
    "Include:": "次を含む：",
    "Includes:": "次を含む：",
    "Exclude which current asset?": "どの流動資産を除外するか",
    "Entitles preferred shareholders to:": "優先株主に次の権利を与える：",
    "Allows the corporation to:": "法人に次を可能にする：",
    "Means each preferred share can be converted into:": "各優先株式は次に転換できることを意味する：",
    "Are treated similarly to:": "次に類似して扱われる：",
    "Is allocated to:": "次に配分される：",
    "Is most appropriate for:": "次に最も適している：",
    "Represents:": "次を表す：",
    "Summarizes:": "次を要約する：",
    "Eliminates the need to track:": "次の追跡を不要にする：",
    "Calculates a new average cost after each:": "次の後に新しい平均原価を計算する：",
    "Is typically:": "通常は次である：",
    "Is recorded on the balance sheet as:": "貸借対照表には次として記載される：",
    "On a classified balance sheet": "区分表示貸借対照表において",
    "In a multi-step income statement": "区分損益計算書において",
    "The difference between": "次の違いは",
    "Which of the following is classified as": "次のうちどれが...に分類されるか",
    "Which of the following is NOT": "次のうちどれが...でないか",
    "Which of the following is a": "次のうちどれが...か",
    "Which of the following is the correct treatment": "次のうち正しい処理はどれか",
    "Which statement about": "次のうち...に関する正しい記述はどれか",
    "Which depreciation method results in": "次の減価償却方法のうち...となるものはどれか",
    "Which characteristic distinguishes": "次のうち...を区別する特徴はどれか",
    "A corporation issues": "法人が...を発行する",
    "A company purchases": "企業が...を購入する",
    "A company uses": "企業が...を使用する",
    "A company records": "企業が...を記録する",
    "A company received": "企業が...を受取った",
    "A company sold": "企業が...を売却した",
    "A company paid": "企業が...を支払った",
    "A company writes off": "企業が...を貸倒処理する",
    "A company has": "企業は...を持つ",
    "A company holds": "企業が...を保有する",
    "A company endorses": "企業が...を裏書譲渡する",
    "A company with": "...の企業",
    "A company estimates": "企業が...を見積もる",
    "A company collects": "企業が...を回収する",
    "A company offers": "企業が...を提供する",
    "A company returns": "企業が...を返品する",
    "A company received an advance payment": "企業が前受金を受取った",
    "A company uses the allowance method": "企業が貸倒引当法を使用する",
    "A company uses the percentage-of-sales method": "企業が売上高基準法を使用する",
    "A company uses the periodic inventory system": "企業が定期棚卸法を使用する",
    "A company issues a promissory note": "企業が約束手形を振り出す",
    "A company provides a warranty": "企業が保証を提供する",
    "A company discounts": "企業が...を割引する",
    "A note receivable dishonored": "受取手形が不渡りとなった場合",
    "When a company provides": "企業が...を提供する場合",
    "When a depreciable asset is sold": "減価償却資産が売却された場合",
    "When a depreciable asset is disposed of": "減価償却資産が処分された場合",
    "When overhead is overapplied": "間接費が配賦超過の場合",
    "When actual overhead exceeds": "実際間接費が...を超える場合",
    "When treasury stock is purchased": "自己株式が購入された場合",
    "When finished goods are sold": "製品が売却された場合",
    "When materials are added continuously": "材料が連続的に投入される場合",
    "When using the allowance method": "貸倒引当法を使用する場合",
    "When a company constructs": "企業が...を建設する場合",
    "When a new partner is admitted": "新組合員が加入する場合",
    "When a new partner invests directly": "新組合員が直接出資する場合",
    "Upon partnership liquidation": "組合の清算において",
    "In partnership liquidation": "組合の清算において",
    "In a partnership": "組合において",
    "In a limited partnership": "有限責任組合において",
    "In a labor cost summary": "労務費集計において",
    "In process costing": "工程別原価計算において",
    "In a multi-department": "多工程において",
    "In a production cost report": "生産原価報告書において",
    "In ABC": "活動基準原価計算（ABC）において",
    "In a manufacturing company": "製造業者において",
    "On a manufacturing company's income statement": "製造業者の損益計算書において",
    "For a manufacturing company": "製造業者において",
    "On a classified balance sheet": "区分表示貸借対照表において",
    "A previously written-off account": "以前貸倒処理した売掛金が",
    "Under the straight-line method": "定額法において",
    "Under the declining balance method": "定率法において",
    "Under the sum-of-the-years'-digits method": "級数法において",
    "Under the units of production method": "生産高比例法において",
    "Under the net method": "正味法において",
    "Under the gross method": "総額法において",
    "Under the periodic inventory system": "定期棚卸法において",
    "Under the percentage-of-completion method": "完成率法において",
    "Under the step-down method": "段階法において",
    "Under absorption costing": "吸収原価計算において",
    "Under variable (direct) costing": "変動原価計算において",
    "Under FIFO": "先入先出法（FIFO）において",
    "Under the weighted average method": "加重平均法において",
    "Under job-order costing": "ジョブオーダー原価計算において",
    "Using the weighted average method": "加重平均法を使用した場合",
    "Using FIFO": "FIFOを使用した場合",
    "Using the high-low method": "高低点法を使用した場合",
    "Using the data from the previous question": "前の問題のデータを使用して",
    "The most appropriate allocation base": "最も適切な配賦基準",
    "A manufacturer's cost of goods sold": "製造業者の売上原価",
    "A change in the estimated useful life": "見積耐用年数の変更",
    "A key difference between": "次の間の重要な違いは",
    "The date of record": "基準日",
    "The payment date": "支払日",
    "Total stockholders' equity": "総株主資本",
    "The total employer burden": "総雇主負担",
    "The half-year convention": "半期規約",
    "A large stock dividend": "大規模株式配当",
    "A 2-for-1 stock split": "1:2の株式分割",
    "The sales value at split-off method": "分離点売価法",
    "The split-off point": "分離点",
    "Joint products are": "結合製品とは",
    "Process costing is most appropriate for": "工程別原価計算は次に最も適している",
    "Job-order costing is most appropriate for": "ジョブオーダー原価計算は次に最も適している",
    "Operation costing is a hybrid of": "オペレーション原価計算は次のハイブリッドである",
    "A cost pool is": "コストプールとは",
    "Spoilage in job-order costing": "ジョブオーダー原価計算の仕損は",
    "Normal spoilage in process costing": "工程別原価計算の正常仕損は",
    "Transferred-in costs in a second processing department": "第2工程の振替原価は",
    "A production cost report summarizes:": "生産原価報告書は次を要約する：",
    "In a production cost report, the 'cost reconciliation' section verifies that:": "生産原価報告書の原価配分の検証セクションは次を確認する：",
    "A company uses backflush costing": "企業がバックフラッシュ原価計算を使用する場合",
    "A company uses standard costing": "企業が標準原価計算を使用する場合",
    "The predetermined overhead rate is calculated as:": "予定間接費配賦率は次のように計算される：",
    "The entry to apply overhead to production is:": "間接費を生産に配賦する仕訳は：",
    "Which of the following is typically included in factory overhead?": "次のうち通常製造間接費に含まれるものはどれか",
    "A company uses a plant-wide overhead rate. This means:": "全工場一括配賦率を使用する場合、次を意味する：",
    "Departmental overhead rates are more accurate than a plant-wide rate because:": "部門間接費率が全工場一括配賦率より正確な理由は：",
    "Activity-based costing (ABC) differs from traditional costing in that ABC:": "ABCが伝統的原価計算と異なる点は次のどれか",
    "If overhead is significantly underapplied, the best treatment is to prorate it among:": "配賦不足が重要な場合の最善の処理は次に按分すること：",
    "The most appropriate allocation base for a highly automated factory is likely:": "高度に自動化された工場に最も適切な配賦基準は次のどれか",
    "Actual overhead costs are recorded by debiting:": "実際間接費コストは次に借方記録される",
    "Depreciation on factory equipment is recorded as:": "工場設備の減価償却費は次のように記録される",
    "Service department costs are allocated to production departments using methods such as:": "補助部門費は次の方法で生産部門に配賦される",
    "The high-low method is used to:": "高低点法は次に使用される",
    "The direct method, step-down method, and reciprocal method": "直接法、段階法、相互配賦法",
    "FIFO method and weighted average method": "先入先出法と加重平均法",
    "High-low method and regression analysis": "高低点法と回帰分析",
    "Job-order method and process method": "ジョブオーダー法と工程別法",
    "Prime costs plus conversion costs equal:": "素原価に加工費を加えると次になる",
    "The difference between normal costing and actual costing is that normal costing uses:": "正常原価計算と実際原価計算の違いは次のどれか",
    "Which of the following is NOT a common overhead allocation base?": "次のうち一般的な間接費配賦基準でないものはどれか",
    "In a just-in-time (JIT) inventory system, raw materials inventory is typically:": "JIT棚卸システムにおいて原材料棚卸資産は通常次である",
    "The difference between direct and indirect materials is that:": "直接材料と間接材料の違いは次のどれか",
    "Freight on raw materials purchased is recorded as:": "原材料仕入の運賃は次のように記録される",
    "Excess materials returned from the factory to the warehouse are recorded as:": "工場から倉庫に返却された余剰材料は次のように記録される",
    "Scrap material from production that has some resale value should be recorded as:": "再販価値のある生産仕損品は次のように記録される",
    "A physical count of raw materials reveals": "原材料の実地棚卸で次が判明した場合",
    "A purchase discount": "仕入割引",
    "Purchase discounts on raw materials": "原材料の仕入割引",
    "Under the perpetual system": "継続記録法において",
    "The journal entry to close net income to partners' capital accounts": "純利益を組合員の資本勘定に閉じる仕訳",
    "Which characteristic distinguishes a partnership from a corporation?": "組合と法人を区別する特徴は次のどれか",
    "A partnership agreement provides": "組合契約で次が定められている場合",
    "A partnership income is taxed:": "組合の所得は次のように課税される",
    "In a partnership liquidation statement": "組合清算計算書において",
    "A partner's capital statement is similar to:": "組合員の資本変動計算書は次に類似する",
    "A company issues stock with a subscription agreement": "企業が株式引受契約で株式を発行する場合",
    "A corporation declares a property dividend": "法人が現物配当を宣言する場合",
    "Which of the following best describes 'legal capital'?": "法定資本を最も適切に説明するものはどれか",
    "A corporation donates treasury stock to employees as a bonus": "法人が自己株式を従業員にボーナスとして寄贈する場合",
    "A company issued a promissory note payable": "企業が約束手形を振り出した場合",
    "A company discounted a customer's note at the bank": "企業が顧客の手形を銀行で割引した場合",
    "A company offers a 5% quantity discount": "企業が5%の数量値引を提供する場合",
    "A company records credit card sales": "企業がクレジットカード売上を記録する場合",
    "A company writes off a": "企業が...を貸倒処理する場合",
    "A company endorses and transfers a note receivable": "企業が受取手形を裏書譲渡する場合",
    "A company sold goods for": "企業が...で商品を売却した場合",
    "A company with a December 31 year-end": "12月31日決算の企業",
    "A company uses the allowance method using the aging of receivables approach": "aging法の貸倒引当法を使用する企業",
    "A company estimates bonus expense": "企業が賞与費用を見積もる場合",
    "A company is constructing a building": "企業が建物を自家建設する場合",
    "A company purchased goods for": "企業が...で商品を購入した場合",
    "Freight costs paid by the seller for goods shipped FOB destination": "FOB乙地条件で売主が支払う運賃",
    "Interest on a note payable is classified": "支払手形の利息は次のように分類される",
    "A note receivable dishonored at maturity": "満期時に不渡りとなった受取手形",
    "A company's allowance for doubtful accounts": "企業の貸倒引当金",
    "A construction project has costs of": "建設プロジェクトのコストが",
    "A company has outstanding checks": "企業に未決済小切手がある場合",
    "Overstating beginning inventory": "期首棚卸資産の過大計上",
    "Failure to record accrued revenue": "未収収益の計上漏れ",
    "Failure to record depreciation expense": "減価償却費の計上漏れ",
    "Failure to accrue wages payable": "未払給与の見落とし",
    "An error in counting ending inventory": "期末棚卸の計数誤り",
    "Which of the following errors would NOT be discovered by trial balance preparation?": "次のうち試算表作成では発見できない誤りはどれか",
    "A corporation issues common stock for services received": "法人が役務の対価として株式を発行する場合",
    "A corporation liquidates treasury stock by formally retiring it": "法人が自己株式を正式に廃棄する場合",
    "A corporation's retained earnings statement shows": "法人の繰越利益剰余金計算書が次を示す場合",
    "Callable preferred stock": "償還優先株式",
    "Convertible preferred stock with a conversion ratio of": "転換比率...の転換優先株式",
    "A company uses normal costing applies overhead": "企業が正常原価計算で間接費を配賦する場合",
    "Moving average method for materials": "材料の移動平均法",
    "Spoiled goods in production that are considered normal": "正常とみなされる生産中の仕損品",
    "A materials ledger card using FIFO": "FIFOの材料元帳",
    "In process costing, materials are added at the beginning of the process": "工程別原価計算で材料が工程始点で投入される場合",
    "Backflush costing system": "バックフラッシュ原価計算システム",
    "Total labor cost variance can be decomposed into": "総労務費差異は次に分解できる",
    "Bonuses paid to factory production supervisors": "工場生産監督者へのボーナス",
    "Learning curve theory suggests": "学習曲線理論によれば",
    "A time study determines": "時間研究で次が判定された場合",
    "A differential piece-rate system": "差別歩合制",
    "Shift premium (night shift differential)": "シフト割増（夜勤差額）",
    "In a labor cost summary": "労務費集計において",
    "When payroll is recorded": "給与記録時に",
    "Employer's payroll taxes for factory workers": "工場労働者の雇主負担給与税",
    "Vacation pay and holiday pay": "有給休暇と祝日給与",
    "A guaranteed wage plan provides": "保証賃金制では次が提供される",
    "Labor cost allocation based on time tickets": "作業時間票に基づく労務費配賦",
    "Piece-rate wages": "歩合制賃金",
    "Payroll entries for factory workers": "工場労働者の給与仕訳",
    "Idle time (workers waiting for materials or machine breakdown)": "アイドルタイム（材料待ちや機械故障での待機時間）",
    "A worker earns": "労働者が...を稼得する場合",
    "Overtime premium paid to factory workers": "工場労働者の残業割増賃金",
    "The employer's share of social insurance premiums (employer burden)": "雇主の社会保険料負担",
    "Gross pay is": "総支給額が...の場合",
    "Indirect labor costs such as factory supervisor salaries": "工場監督者の給与などの間接労務費",
    "Direct labor costs incurred in production": "生産で発生した直接労務費",
    "Using the weighted average method with the same data:": "同じデータで加重平均法を使用した場合：",
    "A materials purchase return of": "材料仕入戻しが...の場合",
    "A materials requisition shows": "材料出庫票が次を示す場合",
    "A company uses FIFO for raw materials": "企業が原材料にFIFOを使用する場合",
    "Raw materials are purchased on credit for": "原材料を...で掛け仕入した場合",
    "When direct materials are requisitioned for production": "直接材料が生産のために払い出された場合",
    "When indirect materials are requisitioned": "間接材料が払い出された場合",
}

# Sort by length (longest first) for better replacement
sorted_terms = sorted(T.items(), key=lambda x: len(x[0]), reverse=True)

def translate_text(text):
    """Translate English text to Japanese using the dictionary."""
    if not text:
        return text
    
    # Skip if already mostly Japanese
    japanese_chars = sum(1 for c in text if '\u3040' <= c <= '\u30ff' or '\u4e00' <= c <= '\u9fff')
    if japanese_chars > len(text) * 0.3:
        return text
    
    result = text
    for eng, jpn in sorted_terms:
        # Case-insensitive replacement
        pattern = re.compile(re.escape(eng), re.IGNORECASE)
        # Preserve case of first letter
        def replacer(match):
            matched = match.group(0)
            if matched[0].isupper() and len(jpn) > 0:
                return jpn
            return jpn
        result = pattern.sub(replacer, result)
    
    return result

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    translated = 0
    for q in data:
        q['question'] = translate_text(q['question'])
        for opt in q['options']:
            opt['text'] = translate_text(opt['text'])
        translated += 1
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"  Translated {translated} questions in {filepath}")
    return translated

# Process files
base = r'C:\Users\haro\.openclaw\workspace\boki2-study\src\data'
files = [
    f'{base}/boki2-exam-financial.json',
    f'{base}/boki2-exam-materials.json',
    f'{base}/boki2-exam-overhead.json',
    f'{base}/boki2-exam-corp.json',
    f'{base}/boki2-exam-advjournal.json',
    f'{base}/boki2-exam-product.json',
]

total = 0
for f in files:
    total += translate_file(f)

print(f"\nTotal translated: {total} questions across {len(files)} files")
